template: remove use_color from template functions.
This catches these functions up with

  commit 2c8c64a90009b50ee9f9708846b29c1f3b53a28f
  Author: W. Trevor King <wking@tremily.us>
  Date:   Sat Sep 1 19:14:12 2012 -0400

    color: add ColoredFormatter for more transparent coloring.

and avoids

  TypeError: send_emails() got an unexpected keyword argument 'use_color'